### ISSUE TITLE
Specify Issue Type for Notion Integration

### ISSUE THREAD

**Issue by asabaal** [asabaal/soundclash#4]
Perplexity recommends the following specification in the `.github/workflows/notion-sync.yml` file:

```yaml
on:
  issues:
    types: [opened, closed, reopened, edited]
```
