### ISSUE TITLE
Switch to Github-issue-2-Notion

### ISSUE THREAD

**Issue by asabaal** [asabaal/soundclash#8]
Perplexity recommended this as an alternative for the uses.

Details for how to use it can be found here:
https://github.com/Edit-Mr/GitHub-issue-2-Notion.

File reproduced here for convenience:

```yaml
name: Sync issues to Notion

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Notion GitHub Issues Automation
        uses: Edit-Mr/GitHub-issue-2-Notion@main
        with:
            repo: ${{ github.repository }}
            NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
            NOTION_DATABASE: ${{ secrets.NOTION_DATABASE_ID }}
```
